### ISSUE TITLE
Create AnswerBar

### ISSUE THREAD

**Issue by arist0cles** [PaperHat/legal-checkup-client#4]
The Answer Bar displays:
- Possible answers to the active question ("Yes", "No", and "Not sure")
- Follows the designs to the pixel

Behaviour:
- User can select an answer to the active question
- On selection of an answer, the answer is recorded [in global state]
- Where an answer is already recorded for the active question, the previously recorded answer is indicated in the code (UX/UI design to be defined)

-------------------------------------------------------------------
PREVIOUSLY:
Yes/No/Don't know

**Comment by hanapc** [comment]
Mostly done - not tested.
