### ISSUE TITLE
Create Mobile ProgressBar

### ISSUE THREAD

**Issue by arist0cles** [PaperHat/legal-checkup-client#5]
UPDATED ACCEPTANCE CRITERIA - MOBILE VIEW ONLY:
- User can identify the 'TOPIC' for the active question
- When the user moves to a unlocked question the active question is updated [in the global state]
- User can navigate using the arrow buttons to 'unlocked' questions (see unlocked criteria below)
- User cannot navigate to Locked questions
- If the 'next' question is locked, the forward button is disabled. 
- Matches the design to the pixel

LOCKED/UNLOCKED QUESTION STATUS RULES:
- Questions where question # is < # answered questions + 1 = Unlocked
- Questions where question # is > # of answered questions +1 = Locked

----------------------------------------------------------------------------
PREVIOUS ACCEPTANCE CRITERIA:
- Do some cool stuff
- Total number of questions + Current question
- Current question is highlighted
- Provides forward/back navigation

**Comment by hanapc** [comment]
100% coverage :)
