### ISSUE TITLE
Ensure all styled components have snapshot test

### ISSUE THREAD

**Issue by hanapc** [PaperHat/legal-checkup-client#51]
Acceptance Criteria:
* All styled components have snapshot test

- [x] DesktopNextButton
- [x] DesktopPreviousButton
- [x] DesktopProgressBar
- [x] DesktopQuestionButton
- [x] LinkExternal
- [x] LinkInternal
- [x] MobileNextButton
- [x] MobilePreviousButton
- [x] QuestionCounter

**Comment by jsmld** [comment]
This story is ready for testing/BAT
